# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

productPowerMinusHalf <- function(vec) {
    .Call(`_SKFCPD_productPowerMinusHalf`, vec)
}

Construct_W0_matern_5_2_one_dim <- function(lambda) {
    .Call(`_SKFCPD_Construct_W0_matern_5_2_one_dim`, lambda)
}

Construct_G_matern_5_2_one_dim <- function(delta_x, lambda) {
    .Call(`_SKFCPD_Construct_G_matern_5_2_one_dim`, delta_x, lambda)
}

Construct_W_matern_5_2_one_dim <- function(delta_x, lambda) {
    .Call(`_SKFCPD_Construct_W_matern_5_2_one_dim`, delta_x, lambda)
}

Construct_G_W_W0_V <- function(d, gamma, eta, kernel_type, is_initial) {
    .Call(`_SKFCPD_Construct_G_W_W0_V`, d, gamma, eta, kernel_type, is_initial)
}

Construct_G_matern_5_2_fastGP <- function(delta_x, lambda) {
    .Call(`_SKFCPD_Construct_G_matern_5_2_fastGP`, delta_x, lambda)
}

Construct_W_matern_5_2_fastGP <- function(delta_x, lambda, W0) {
    .Call(`_SKFCPD_Construct_W_matern_5_2_fastGP`, delta_x, lambda, W0)
}

Construct_G_exp_fastGP <- function(delta_x, lambda) {
    .Call(`_SKFCPD_Construct_G_exp_fastGP`, delta_x, lambda)
}

Construct_W_exp_fastGP <- function(delta_x, lambda, W0) {
    .Call(`_SKFCPD_Construct_W_exp_fastGP`, delta_x, lambda, W0)
}

Construct_W0_exp_one_dim <- function(lambda) {
    .Call(`_SKFCPD_Construct_W0_exp_one_dim`, lambda)
}

Get_Q_K <- function(GG, W, C0, VV) {
    .Call(`_SKFCPD_Get_Q_K`, GG, W, C0, VV)
}

Get_log_det_S2_one_dim <- function(param, have_noise, delta_x, output, kernel_type) {
    .Call(`_SKFCPD_Get_log_det_S2_one_dim`, param, have_noise, delta_x, output, kernel_type)
}

KF_ini <- function(cur_input, d, gamma, eta, kernel_type, G_W_W0_V) {
    .Call(`_SKFCPD_KF_ini`, cur_input, d, gamma, eta, kernel_type, G_W_W0_V)
}

KF_ini_for_profile_like <- function(cur_input, d, gamma, eta, kernel_type, G_W_W0_V) {
    .Call(`_SKFCPD_KF_ini_for_profile_like`, cur_input, d, gamma, eta, kernel_type, G_W_W0_V)
}

get_LY_online <- function(cur_input, prev_param, eta, G_W_W0_V) {
    .Call(`_SKFCPD_get_LY_online`, cur_input, prev_param, eta, G_W_W0_V)
}

KF_param_update_for_profile_like <- function(cur_input, cur_num_obs, prev_param, d, gamma, eta, kernel_type, G_W_W0_V) {
    .Call(`_SKFCPD_KF_param_update_for_profile_like`, cur_input, cur_num_obs, prev_param, d, gamma, eta, kernel_type, G_W_W0_V)
}

get_predictive_dist_KF_objective_prior <- function(cur_input, cur_num_obs, params, prev_L, d, gamma, model_type, mu, sigma_2, eta, kernel_type) {
    .Call(`_SKFCPD_get_predictive_dist_KF_objective_prior`, cur_input, cur_num_obs, params, prev_L, d, gamma, model_type, mu, sigma_2, eta, kernel_type)
}

get_predictive_dist_direct_objective_prior <- function(cur_input_seq, d, gamma, mu, sigma_2, eta) {
    .Call(`_SKFCPD_get_predictive_dist_direct_objective_prior`, cur_input_seq, d, gamma, mu, sigma_2, eta)
}

GaSP_CPD_pred_dist_objective_prior_KF_online <- function(KF_params, prev_L_params, cur_point, d, gamma, model_type, mu, sigma_2, eta, kernel_type, G_W_W0_V_ini, G_W_W0_V) {
    .Call(`_SKFCPD_GaSP_CPD_pred_dist_objective_prior_KF_online`, KF_params, prev_L_params, cur_point, d, gamma, model_type, mu, sigma_2, eta, kernel_type, G_W_W0_V_ini, G_W_W0_V)
}

GaSP_CPD_pred_dist_objective_prior_direct_online <- function(cur_seq, d, gamma, eta, mu, sigma_2) {
    .Call(`_SKFCPD_GaSP_CPD_pred_dist_objective_prior_direct_online`, cur_seq, d, gamma, eta, mu, sigma_2)
}

CPD_DLM <- function(design, response, gamma, model_type, mu, sigma_2, eta, kernel_type, stop_at_first_cp, hazard_vec, truncate_at_prev_cp) {
    .Call(`_SKFCPD_CPD_DLM`, design, response, gamma, model_type, mu, sigma_2, eta, kernel_type, stop_at_first_cp, hazard_vec, truncate_at_prev_cp)
}

